title: ~rpthibeault
url: "https://rpthibeault.github.io"
baseurl: "" # Keep empty for root domain
description: "Personal blog"
permalink: /:title/
markdown: kramdown
theme: null
timezone: America/Montreal

# Enable line numbers in code blocks
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true
